### PR TITLE
Upgrade AWS EC2 Instance from t2.micro to t3a.small for Increased RAM

### PR DESCRIPTION
**Pull request by kavi-99**

### CODE REVIEW

**Comment by yulinzou** [comment]
It seems like it didn't pass the syntax and integration checks.

**Comment by kavi-99** [comment]
> It seems like it didn't pass the syntax and integration checks.

Hi, yes I just checked, the syntax check I am not able to figure out, but I think its because the use of some functions in the .go files has been deprecated. These files have not been changed for this commit. This commit only changes the workflow file under the folder, .github/workflows.
I was able to resolve the integration error

**Comment by kavi-99** [comment]
> > It seems like it didn't pass the syntax and integration checks.
> 
> Hi, yes I just checked, the syntax check I am not able to figure out, but I think its because the use of some functions in the .go files has been deprecated. These files have not been changed for this commit. This commit only changes the workflow file under the folder, .github/workflows. I was able to resolve the integration error

The syntax checks should also be okay now

**Review by yulinzou — APPROVED** [review]
LGTM

**Pull request merged**
